plugins {
    id 'io.nextflow.nextflow-plugin' version '1.0.0-beta.10'
}

version = '0.5.1'

repositories {
    mavenCentral()
    maven {
        name = 'unidata-all'
        url = 'https://artifacts.unidata.ucar.edu/repository/unidata-all/'
    }
}

configurations {
    // Exclude libraries provided by Nextflow at runtime to avoid PF4J classloader conflicts
    runtimeClasspath.exclude group: 'org.slf4j', module: 'slf4j-api'
    runtimeClasspath.exclude group: 'com.google.guava', module: 'guava'
    runtimeClasspath.exclude group: 'com.google.guava', module: 'failureaccess'
    runtimeClasspath.exclude group: 'com.google.guava', module: 'listenablefuture'
}

dependencies {
    implementation 'io.jhdf:jhdf'
    implementation 'dev.zarr:zarr-java:0.1.4-SNAPSHOT'
    // SLF4J is provided by Nextflow at runtime
    compileOnly 'org.slf4j:slf4j-api:2.0.17'
}

nextflowPlugin {
    nextflowVersion = '24.10.0'

    provider = 'Nico Trummer'
    className = 'acme.plugin.AnnDataPlugin'
    extensionPoints = [
        'acme.plugin.AnnDataExtension'
    ]

}
